stages:
  - setup
  - test
  - deploy

variables:
  NODE_IMAGE: node:16-alpine

.template: &template
  stage: deploy
  image: google/cloud-sdk
  before_script:
    - echo ${KUBE_ACCOUNT_KEY} | base64 -di > key.json
  script:
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project oecd-228113
    - gcloud config set container/cluster oecd
    - gcloud config set compute/region europe-west1
    - gcloud container clusters get-credentials oecd --region europe-west1-b
    - gsutil -m rsync -d -r ./i18n gs://$ENV-i18n-siscc
  environment:
    name: $ENV
  tags:
    - kube
    - oecd

setup:
  stage: setup
  image: $NODE_IMAGE
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/

test-json:
  stage: test
  image: $NODE_IMAGE
  script: yarn i18n:json-validate

deploy-qa:
  variables:
    ENV: qa
  <<: *template
  only:
    - develop

deploy-staging:
  variables:
    ENV: staging
  <<: *template
  only:
    - master
